CREATE TABLE PACIENTE (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome varchar(255),
    email varchar(255),
    telefone varchar(255),
    cpf varchar(255)
);

CREATE TABLE MEDICO (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(255)
);

CREATE TABLE CONSULTA(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	id_medico BIGINT,
	id_paciente BIGINT,
	data date
);
ALTER TABLE CONSULTA ADD FOREIGN KEY (id_medico) REFERENCES MEDICO(id);
ALTER TABLE CONSULTA ADD FOREIGN KEY (id_paciente) REFERENCES PACIENTE(id);
INSERT INTO PACIENTE (id,nome,email,telefone,cpf) VALUES (4,'Rafael','rafael.ahrons@gmail.com','5185005657','99999999');