CREATE TABLE PACIENTE (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome varchar(255),
    email varchar(255),
    telefone varchar(255),
    cpf varchar(255)
);

CREATE TABLE MEDICO (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(255)
);

CREATE TABLE CONSULTA(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	id_medico BIGINT,
	id_paciente BIGINT,
	id_preco BIGINT,
	data date
);
ALTER TABLE CONSULTA ADD FOREIGN KEY (id_medico) REFERENCES MEDICO(id);
ALTER TABLE CONSULTA ADD FOREIGN KEY (id_paciente) REFERENCES PACIENTE(id);

CREATE TABLE USERS (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY,
 username varchar(256),
 password varchar(256),
 enabled boolean
);

CREATE TABLE AUTHORITIES (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY,
 username varchar(256),
 authority varchar(256)
);

CREATE TABLE PRECOS(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	valor BIGINT,
	nome varchar(255),
	descricao varchar(255)
);

ALTER TABLE CONSULTA ADD FOREIGN KEY (id_preco) REFERENCES PRECOS(id);

INSERT INTO USERS (username, password, enabled) values ('user', 'user', true);
INSERT INTO AUTHORITIES (username, authority) values ('user', 'ROLE_ADMIN');

INSERT INTO PACIENTE (id,nome,email,telefone,cpf) VALUES (4,'Rafael','rafael.ahrons@gmail.com','5185005657','99999999');